name: Build and Release Blazor Server App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch tags
        run: git fetch --tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./RecipeApp/RecipeApp.sln

      - name: Build the project
        run: dotnet build ./RecipeApp/RecipeApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./RecipeApp/RecipeApp.sln --configuration Release --no-restore --verbosity normal

      - name: Publish app
        run: dotnet publish ./RecipeApp/RecipeApp.sln --configuration Release -o publish

      - name: Create git tag and push
        run: |
          git tag ${{ steps.tag_version.outputs.version }}
          git push origin ${{ steps.tag_version.outputs.version }}

      - name: Calculate version tag
        id: tag_version
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          BUILD_NUMBER=${{ github.run_number }}
          
          VERSION=$(printf "%s.%s.%03d" "$YEAR" "$MONTH" "$BUILD_NUMBER")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Generated version: $VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          name: Release ${{ steps.tag_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}