name: Build and Release Blazor Server App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish --configuration Release -o publish

      - name: Calculate version tag
        id: tag_version
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          PREFIX="${YEAR}.${MONTH}"
          
          # Получим все теги, начинающиеся с текущего префикса (например, 2025.05)
          TAGS=$(git tag --list "${PREFIX}.*" | sort -V)
          
          if [ -z "$TAGS" ]; then
            BUILD=1
          else
            LAST_TAG=$(echo "$TAGS" | tail -n 1)
            LAST_BUILD=$(echo "$LAST_TAG" | awk -F '.' '{print $3}')
            BUILD=$((10#$LAST_BUILD + 1))
          fi
          
          VERSION=$(printf "%s.%03d" "$PREFIX" "$BUILD")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Generated version: $VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          name: Release ${{ steps.tag_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload published app to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          files: |
            publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}